### ISSUE TITLE
Claims enabled for nether is not obeyed

### ISSUE THREAD

**Issue by strawmelonjuice** [SuperRonanCraft/Pueblos#4]
I currently have my config.yml file in the following configuration:
```yml
# Pueblos plugin by RonanCraft! (Join my Public Server mc.RonanCraft.net) #
# Need help? go to https://ronancraft.net/discord! #

Language-File: en.yml
DisableUpdater: false
DateFormat: EEE MMM dd, yyyy hh:mm:ss a # More formatting here https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
Claim: # Forced claim options
  Item: golden_shovel
  MaxSize: 256
  MaxDepth: 32
  WorldsEnabled:
  - world
  - the_end
  - the_nether
  - creative
  MaxClaims: 20
Global: # Settings that affect the whole server, not just claims
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  RabbitsEatCrops: true
Player:
  ProtectDeathDrops: false # If a player dies, their items will not be able to be picked up by others
```
and my expectation was that pueblos would allow claims in the nether, yet it tells users:
![this world has claims disabled](https://user-images.githubusercontent.com/101558380/204002662-0930a272-5fa6-4003-bf98-05d0680b5c80.png)
so I'm wondering, is the config file even being read?
